#
# See: http://jekyllrb.com/docs/configuration/
#
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-mentions
    - jekyll-redirect-from

# Do not publish these files with the site build.
exclude: [Gemfile, Gemfile.lock, vendor, README.md, CNAME]

timezone: "Europe/Berlin"

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"
            # The blog navigation is active per default.
            active_navigation: "blog"
            # Show "Edit on GitHub" ribbon?
            edit_link: true
