#
# See: http://jekyllrb.com/docs/configuration/
#
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-mentions
    - jekyll-redirect-from

exclude: [Gemfile, Gemfile.lock, vendor]

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"
