#
# See: http://jekyllrb.com/docs/configuration/
#
gems:
    - jekyll-sitemap
    - jekyll-feed

exclude: [Gemfile, Gemfile.lock]

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"
